CREATE USER [rasasystem] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[rasasystem]
GO
DENY ALTER ANY DATABASE DDL TRIGGER TO [rasasystem]
GRANT CONNECT REPLICATION TO [rasasystem]
GRANT EXECUTE TO [rasasystem]
GRANT SHOWPLAN TO [rasasystem]
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [rasasystem]
GRANT VIEW DATABASE STATE TO [rasasystem]
